# Generated by Django 6.0.2 on 2026-02-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='user_executors/')),
                ('pure_path', models.TextField(blank=True, help_text='Leave blank will be filled after save', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.FileField(upload_to='user_configs/')),
                ('project', models.FileField(upload_to='user_configs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_path', models.TextField(blank=True, help_text='Leave blank will be filled after save', null=True)),
                ('project_path', models.TextField(blank=True, help_text='Leave blank will be filled after save', null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Leave blank will be filled after save', null=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='ansys_api.executor')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FileField(upload_to='calculation_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ansys_api.usertask')),
            ],
        ),
    ]
