# Generated by Django 6.0.2 on 2026-02-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansys_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(blank=True, help_text='Leave blank will be filled after save', null=True, upload_to='graphics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='ansys_api.usertask')),
            ],
        ),
    ]
